#!/bin/bash

# ==============================================================================
# AUTO-GENERATED Cloudflare Tunnel Connectivity Test Script
#
# This script was auto-generated by cf_GenerateTunnelTest.sh by fetching the
# latest endpoint data from the official Cloudflare documentation at:
#   https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-tunnel/configure-tunnels/tunnel-with-firewall/
#
# Tests follow the official Cloudflare connectivity pre-checks guide:
#   https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-tunnel/troubleshoot-tunnels/connectivity-prechecks/
#
# Generated: 2026-03-02 09:20:14 EST
# Generator: cf_GenerateTunnelTest.sh v1.0
# Source:    https://raw.githubusercontent.com/cloudflare/cloudflare-docs/production/src/content/docs/cloudflare-one/networks/connectors/cloudflare-tunnel/configure-tunnels/tunnel-with-firewall.mdx
#
# USAGE
#     ./cf_TunnelTest_generated.sh
#     ./cf_TunnelTest_generated.sh -v
#     ./cf_TunnelTest_generated.sh -v -o results.txt
#     ./cf_TunnelTest_generated.sh -s -o results.txt
#     ./cf_TunnelTest_generated.sh -h
# ==============================================================================

# Define ANSI color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color
CYAN='\033[0;36m'

SCRIPT_NAME="cf_TunnelTest_generated.sh"
SCRIPT_GENERATED="2026-03-02 09:20:14 EST"

# Help function
show_help() {
    cat <<EOF
${SCRIPT_NAME} - Auto-Generated Cloudflare Tunnel Connectivity Pre-Check

SYNOPSIS
    Validates DNS resolution and network connectivity to Cloudflare Tunnel
    endpoints. Auto-generated from the official Cloudflare documentation.

USAGE
    ./${SCRIPT_NAME} [OPTIONS]

OPTIONS
    -h, --help          Show this help message and exit.
    -v                  Verbose mode. Display the exact command run and
                        full output for each test.
    -o <file>           Save output to <file> with ANSI colors stripped.
    -s                  Silent mode. No console output, write only to file.
                        Requires -o.

EXAMPLES
    ./${SCRIPT_NAME}
    ./${SCRIPT_NAME} -v
    ./${SCRIPT_NAME} -v -o results.txt
    ./${SCRIPT_NAME} -s -o results.txt
EOF
    exit 0
}

# Handle --help
for arg in "$@"; do
    [ "$arg" == "--help" ] && show_help
done

# Parse options
OUTPUT_FILE=""
VERBOSE=false
SILENT=false
while getopts ":hsvo:" opt; do
    case $opt in
        h) show_help ;;
        s) SILENT=true ;;
        v) VERBOSE=true ;;
        o) OUTPUT_FILE="$OPTARG" ;;
        \?) echo "Usage: $0 [-h] [-v] [-s] [-o output_file]"; exit 1 ;;
    esac
done

# Silent requires -o
if [ "$SILENT" == true ] && [ -z "$OUTPUT_FILE" ]; then
    echo "Error: -s (silent) requires -o <file>."
    exit 1
fi

# Set up output redirection
if [ "$SILENT" == true ]; then
    exec > >(sed 's/\x1b\[[0-9;]*m//g' > "$OUTPUT_FILE")
    exec 2>&1
elif [ -n "$OUTPUT_FILE" ]; then
    exec > >(tee >(sed 's/\x1b\[[0-9;]*m//g' > "$OUTPUT_FILE"))
    exec 2>&1
fi

# Banner
echo -e "${CYAN}============================================================${NC}"
echo -e "${CYAN}Cloudflare Tunnel Connectivity Pre-Check (Auto-Generated)${NC}"
echo -e "${CYAN}Script:    ${NC}${SCRIPT_NAME}"
echo -e "${CYAN}Generated: ${NC}${SCRIPT_GENERATED}"
echo -e "${CYAN}Hostname:  ${NC}$(hostname)"
echo -e "${CYAN}Run Time:  ${NC}$(date '+%Y-%m-%d %H:%M:%S %Z')"
echo -e "${CYAN}Run As:    ${NC}$(whoami)"
echo -e "${CYAN}Run From:  ${NC}$(pwd)"
echo -e "${CYAN}============================================================${NC}"
echo ""

# ==============================================================================
# Step 2: DNS Resolution Tests
# ==============================================================================

dns_hosts=(
    "region1.v2.argotunnel.com"
    "region2.v2.argotunnel.com"
    "us-region1.v2.argotunnel.com"
    "us-region2.v2.argotunnel.com"
)

echo -e "${YELLOW}Step 2: Running DNS resolution tests with dig...${NC}"
for dns_host in "${dns_hosts[@]}"; do
    cmd="dig +short A $dns_host"
    if [ "$VERBOSE" == true ]; then
        echo -e "  ${CYAN}> $cmd${NC}"
    fi
    dig_output=$(dig +short A "$dns_host" 2>/dev/null)
    if [ -n "$dig_output" ]; then
        first_ip=$(echo "$dig_output" | head -n1)
        echo -e "  dig A $dns_host ... ${GREEN}OK${NC} (e.g. $first_ip)"
        if [ "$VERBOSE" == true ]; then
            echo "$dig_output" | while IFS= read -r line; do echo "    $line"; done
        fi
    else
        echo -e "  dig A $dns_host ... ${RED}FAILED (no A records returned)${NC}"
    fi

    cmd="dig +short AAAA $dns_host"
    if [ "$VERBOSE" == true ]; then
        echo -e "  ${CYAN}> $cmd${NC}"
    fi
    dig_output=$(dig +short AAAA "$dns_host" 2>/dev/null)
    if [ -n "$dig_output" ]; then
        first_ip=$(echo "$dig_output" | head -n1)
        echo -e "  dig AAAA $dns_host ... ${GREEN}OK${NC} (e.g. $first_ip)"
        if [ "$VERBOSE" == true ]; then
            echo "$dig_output" | while IFS= read -r line; do echo "    $line"; done
        fi
    else
        echo -e "  dig AAAA $dns_host ... ${RED}FAILED (no AAAA records returned)${NC}"
    fi
done

echo -e "\n${YELLOW}Step 2.2: Comparing DNS against 1.1.1.1 resolver...${NC}"
for dns_host in "${dns_hosts[@]}"; do
    cmd="dig +short A $dns_host @1.1.1.1"
    if [ "$VERBOSE" == true ]; then
        echo -e "  ${CYAN}> $cmd${NC}"
    fi
    dig_output=$(dig +short A "$dns_host" @1.1.1.1 2>/dev/null)
    if [ -n "$dig_output" ]; then
        first_ip=$(echo "$dig_output" | head -n1)
        echo -e "  dig A $dns_host @1.1.1.1 ... ${GREEN}OK${NC} (e.g. $first_ip)"
        if [ "$VERBOSE" == true ]; then
            echo "$dig_output" | while IFS= read -r line; do echo "    $line"; done
        fi
    else
        echo -e "  dig A $dns_host @1.1.1.1 ... ${RED}FAILED (no A records returned)${NC}"
    fi
done

# ==============================================================================
# Step 3: Network Connectivity Tests
# ==============================================================================

echo -e "\n${YELLOW}Step 3: Starting TCP/UDP connection tests...${NC}"

tests=(
    "region1.v2.argotunnel.com,7844,TCP,Cloudflare Global - region1.v2.argotunnel.com (http2)"
    "region1.v2.argotunnel.com,7844,UDP,Cloudflare Global - region1.v2.argotunnel.com (quic)"
    "region2.v2.argotunnel.com,7844,TCP,Cloudflare Global - region2.v2.argotunnel.com (http2)"
    "region2.v2.argotunnel.com,7844,UDP,Cloudflare Global - region2.v2.argotunnel.com (quic)"
    "_v2-origintunneld._tcp.argotunnel.com,7844,TCP,Cloudflare Global - _v2-origintunneld._tcp.argotunnel.com (http2)"
    "cftunnel.com,7844,TCP,Cloudflare Global - cftunnel.com (http2)"
    "cftunnel.com,7844,UDP,Cloudflare Global - cftunnel.com (quic)"
    "h2.cftunnel.com,7844,TCP,Cloudflare Global - h2.cftunnel.com (http2)"
    "quic.cftunnel.com,7844,UDP,Cloudflare Global - quic.cftunnel.com (quic)"
    "us-region1.v2.argotunnel.com,7844,TCP,Cloudflare US Region - us-region1.v2.argotunnel.com (http2)"
    "us-region1.v2.argotunnel.com,7844,UDP,Cloudflare US Region - us-region1.v2.argotunnel.com (quic)"
    "us-region2.v2.argotunnel.com,7844,TCP,Cloudflare US Region - us-region2.v2.argotunnel.com (http2)"
    "us-region2.v2.argotunnel.com,7844,UDP,Cloudflare US Region - us-region2.v2.argotunnel.com (quic)"
    "api.cloudflare.com,443,TCP,Optional - api.cloudflare.com (HTTPS)"
    "update.argotunnel.com,443,TCP,Optional - update.argotunnel.com (HTTPS)"
    "github.com,443,TCP,Optional - github.com (HTTPS)"
    "github.com,443,TCP,Optional - github.com (HTTPS)"
    "pqtunnels.cloudflareresearch.com,443,TCP,Optional - pqtunnels.cloudflareresearch.com (HTTPS)"
    "1.1.1.1,53,UDP,Cloudflare DNS (1.1.1.1)"
    "1.0.0.1,53,UDP,Cloudflare DNS (1.0.0.1)"
)

for test_case in "${tests[@]}"; do
    hostname=$(echo "$test_case" | cut -d',' -f1)
    port=$(echo "$test_case" | cut -d',' -f2)
    protocol=$(echo "$test_case" | cut -d',' -f3)
    description=$(echo "$test_case" | cut -d',' -f4)

    echo -n "  Testing $hostname:$port ($protocol) - $description..."

    is_successful=false
    nc_cmd=""
    nc_output=""

    if [ "$protocol" == "UDP" ]; then
        nc_cmd="nc -uvz -w 3 $hostname $port"
        nc_output=$(nc -uvz -w 3 "$hostname" "$port" 2>&1)
        [ $? -eq 0 ] && is_successful=true
    elif [ "$protocol" == "TCP" ]; then
        nc_cmd="nc -vz -w 3 $hostname $port"
        nc_output=$(nc -vz -w 3 "$hostname" "$port" 2>&1)
        [ $? -eq 0 ] && is_successful=true
    else
        echo -e " ${RED}Unknown protocol '$protocol'. Skipping.${NC}"
        continue
    fi

    if [ "$is_successful" == true ]; then
        echo -e " ${GREEN}PASSED${NC}"
    else
        echo -e " ${RED}FAILED${NC}"
    fi

    if [ "$VERBOSE" == true ]; then
        echo -e "    ${CYAN}> $nc_cmd${NC}"
        if [ -n "$nc_output" ]; then
            echo "$nc_output" | while IFS= read -r line; do echo "      $line"; done
        fi
    fi
done

echo -e "\n${YELLOW}All tests complete.${NC}"
